import type { Metadata } from "next";
import "./globals.css";
import { Sarabun } from "next/font/google";
import "leaflet/dist/leaflet.css";

//import font
const sarabun = Sarabun({
  subsets: ["thai", "latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
    <html
        lang="th"
        className={`${sarabun.className} h-full antialiased`}
    >
        <body className="min-h-screen">{children}</body>
    </html>
    );
}